# Assign inputs/outputs to actual pins on the FPGA
set_property PACKAGE_PIN M15 [get_ports CLK]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {CLK}]
set_property PACKAGE_PIN F22 [get_ports Parallel_In[0]]
set_property PACKAGE_PIN G22 [get_ports Parallel_In[1]] 
set_property PACKAGE_PIN H22 [get_ports Parallel_In[2]]
set_property PACKAGE_PIN F21 [get_ports Parallel_In[3]]  
set_property PACKAGE_PIN H19 [get_ports Shift_In]  
set_property PACKAGE_PIN H18 [get_ports Shift_Enable]  
set_property PACKAGE_PIN H17 [get_ports Load]
set_property PACKAGE_PIN T22 [get_ports Reg_Content[0]]  
set_property PACKAGE_PIN T21 [get_ports Reg_Content[1]]  
set_property PACKAGE_PIN U22 [get_ports Reg_Content[2]]  
set_property PACKAGE_PIN U21 [get_ports Reg_Content[3]]
set_property PACKAGE_PIN W22 [get_ports Shift_Out]  

# Define voltage levels (3.3 for LEDs and 1.8 for Switches)
set_property IOSTANDARD LVCMOS18 [get_ports CLK] 
set_property IOSTANDARD LVCMOS18 [get_ports Parallel_In[0]]
set_property IOSTANDARD LVCMOS18 [get_ports Parallel_In[1]]
set_property IOSTANDARD LVCMOS18 [get_ports Parallel_In[2]]
set_property IOSTANDARD LVCMOS18 [get_ports Parallel_In[3]] 
set_property IOSTANDARD LVCMOS18 [get_ports Shift_In] 
set_property IOSTANDARD LVCMOS18 [get_ports Shift_Enable]
set_property IOSTANDARD LVCMOS18 [get_ports Load] 
set_property IOSTANDARD LVCMOS33 [get_ports Reg_Content[0]] 
set_property IOSTANDARD LVCMOS33 [get_ports Reg_Content[1]]
set_property IOSTANDARD LVCMOS33 [get_ports Reg_Content[2]]
set_property IOSTANDARD LVCMOS33 [get_ports Reg_Content[3]]
set_property IOSTANDARD LVCMOS33 [get_ports Shift_Out]
