# Assign inputs/outputs to actual pins on the FPGA
set_property PACKAGE_PIN N15 [get_ports CLK]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {CLK}]
set_property PACKAGE_PIN R18 [get_ports reset]
set_property PACKAGE_PIN F22 [get_ports user_addr[0]]
set_property PACKAGE_PIN G22 [get_ports user_addr[1]]
set_property PACKAGE_PIN H22 [get_ports user_addr[2]]
set_property PACKAGE_PIN F21 [get_ports user_addr[3]]
set_property PACKAGE_PIN H19 [get_ports user_addr[4]]
set_property PACKAGE_PIN H18 [get_ports reg_bits[0]]
set_property PACKAGE_PIN H17 [get_ports reg_bits[1]]
set_property PACKAGE_PIN T22 [get_ports register_out_user[0]]  
set_property PACKAGE_PIN T21 [get_ports register_out_user[1]]  
set_property PACKAGE_PIN U22 [get_ports register_out_user[2]]  
set_property PACKAGE_PIN U21 [get_ports register_out_user[3]]
set_property PACKAGE_PIN V22 [get_ports register_out_user[4]]
set_property PACKAGE_PIN W22 [get_ports register_out_user[5]]
set_property PACKAGE_PIN U19 [get_ports register_out_user[6]]
set_property PACKAGE_PIN U14 [get_ports register_out_user[7]]
 

# Define voltage levels (3.3 for LEDs and 1.8 for Switches)
set_property IOSTANDARD LVCMOS18 [get_ports CLK]  
set_property IOSTANDARD LVCMOS18 [get_ports reset]
set_property IOSTANDARD LVCMOS18 [get_ports user_addr[0]]
set_property IOSTANDARD LVCMOS18 [get_ports user_addr[1]]
set_property IOSTANDARD LVCMOS18 [get_ports user_addr[2]]
set_property IOSTANDARD LVCMOS18 [get_ports user_addr[3]]
set_property IOSTANDARD LVCMOS18 [get_ports user_addr[4]]
set_property IOSTANDARD LVCMOS18 [get_ports reg_bits[0]]
set_property IOSTANDARD LVCMOS18 [get_ports reg_bits[1]]
set_property IOSTANDARD LVCMOS33 [get_ports register_out_user[0]] 
set_property IOSTANDARD LVCMOS33 [get_ports register_out_user[1]]
set_property IOSTANDARD LVCMOS33 [get_ports register_out_user[2]]
set_property IOSTANDARD LVCMOS33 [get_ports register_out_user[3]]
set_property IOSTANDARD LVCMOS33 [get_ports register_out_user[4]]
set_property IOSTANDARD LVCMOS33 [get_ports register_out_user[5]]
set_property IOSTANDARD LVCMOS33 [get_ports register_out_user[6]]
set_property IOSTANDARD LVCMOS33 [get_ports register_out_user[7]]
